### ISSUE TITLE
Handling Nested Objects 

### ISSUE THREAD

**Issue by jesse-villafane** [securedeveloper/react-data-export#59]
In the provided examples, the json object is flat. If you want to use a dataset with nested objects, be aware that it may not be so clear how to access the nested object attribute.

Here is the structure of my dataset:

**activitiesList**
`[{
            "id": 1,
            "activityName": "My Fundraiser"
            "organization": {
                "id": 10,
                "organizationName": "My  Organization",
      },
{
            "id": 2,
            "activityName": "My Fundraiser 2"
            "organization": {
                "id": 10,
                "organizationName": "My  Organization",
      }]
         ` 

I tried to pickup the organization's id as **organization.id** but it didn't work.   

```
<ExcelSheet data={activitiesList} name="Activities">
                    <ExcelColumn label="Organization ID" value="organization.id"/>
                </ExcelSheet>
```
I found that a way to do it is the following:

```
<ExcelSheet data={activitiesList} name="Activities">
                    <ExcelColumn label="Organization ID" value={(col) => col.organization.organizationInitials}/>
                </ExcelSheet>
```

It would be helpful if we could show an example of how to deal with nested objects. 

Thanks!

**Comment by securedeveloper** [comment]
Hello @jesse-villafane, to access nested object properties you need to pass a callback, which you already did in your 2nd example,

In order to have a styled document, you need to pass a multidimensional  array of objects with specified properties. (which means you have to pass a ready dataset to the library).

But again, if you don't care about document styling go with 1st approach, pass a callback and you can access any nested level of object.

Hope this will hlep.

**Comment by jesse-villafane** [comment]
Excellent, this answers question. Thank you!
